"""Terms of Service and Privacy Policy pages (public, no auth).

Plain-language legal pages for the hosted product. Stripe requires a real ToS + privacy policy
for a live account, and users paying for a service that holds their data expect both. These are
sensible defaults for a small SaaS — review before a serious marketing push, and update the
"Last updated" date on any material change.
"""

from __future__ import annotations

from .templates import page

_UPDATED = "July 14, 2026"
_CONTACT = "support@x-bookmarks.ai"


def terms_page():
    body = f"""
<p class=muted>Last updated: {_UPDATED}</p>

<h3>1. The service</h3>
<p>x-bookmarks.ai ("the service") imports the X (Twitter) bookmarks you authorize us to read,
organizes them with AI, and lets you search, browse, and ask questions about them. The service is
provided by the operator of x-bookmarks.ai ("we").</p>

<h3>2. Your account</h3>
<p>You sign in either with your X account (via X's official OAuth) or with your email via a
one-time link. You're responsible for keeping access to that X account or email secure. You must
be legally able to enter this agreement, and you may only connect an X account you own or are
authorized to use.</p>

<h3>3. Your content</h3>
<p>Your bookmarks remain yours. You grant us only the rights needed to operate the service:
storing, indexing, embedding, and displaying your bookmarks back to you. We never sell your data
or show it to other users.</p>

<h3>4. Free tier, payments, and credits</h3>
<p>The free tier includes importing a limited number of your most recent bookmarks and a limited
number of AI questions per day. Paid features include prepaid <b>imports</b> (each import brings
one saved post into your library; unused imports remain on your account for future syncs) and
prepaid credits consumed per AI question. Payments are processed by Stripe; we never see your
card number. Imports and credits have no cash value and are non-transferable; they are
refundable on request and where required by law — contact us at {_CONTACT} if something went
wrong and we'll make it right.</p>

<h3>5. Acceptable use</h3>
<p>Don't abuse the service: no attempts to access other users' data, probe or overload the
infrastructure, resell access, or use the service in violation of X's terms or applicable law.
We may suspend accounts that do.</p>

<h3>6. AI output</h3>
<p>Answers and categories are generated by AI from your saved posts. They can be wrong or
incomplete. Don't rely on them as professional advice.</p>

<h3>7. Availability and changes</h3>
<p>The service is provided "as is," without warranties. We work to keep it available but don't
guarantee uninterrupted operation, and we may change or discontinue features. To the maximum
extent permitted by law, our total liability is limited to the amount you paid us in the twelve
months before a claim.</p>

<h3>8. Termination</h3>
<p>You can stop using the service and request account deletion at any time (see the Privacy
Policy). We may terminate accounts that violate these terms.</p>

<h3>9. Changes to these terms</h3>
<p>We may update these terms; material changes will be reflected in the date above. Continued use
after a change means you accept the updated terms.</p>

<p>Questions: <a href="mailto:{_CONTACT}">{_CONTACT}</a> ·
<a href="/privacy">Privacy Policy</a></p>
"""
    return page("Terms of Service", body)


def privacy_page():
    body = f"""
<p class=muted>Last updated: {_UPDATED}</p>

<h3>What we collect</h3>
<ul>
<li><b>Your sign-in identity</b> — if you sign in with X: your X user id and handle, used to
recognize your account. If you sign in by email (or provide one at checkout): your email address,
used for sign-in links, receipts, and service messages.</li>
<li><b>Your X bookmarks</b> — the posts you've saved, fetched with your permission via X's
official API after you click "Connect X." We never see your X password.</li>
<li><b>X access tokens</b> — stored encrypted (AWS KMS) and bound to your account; used only to
fetch your bookmarks.</li>
<li><b>Usage records</b> — which AI operations your account ran and their cost, used for the
free-tier limits and credit accounting.</li>
<li><b>Payment data</b> — handled entirely by Stripe. We store only your Stripe customer id and
purchase state, never card numbers.</li>
</ul>

<h3>How we use it</h3>
<p>Solely to operate the service: importing, indexing, and AI-organizing <i>your</i> bookmarks and
answering <i>your</i> questions about them. We do not sell your data, share it with other users,
or use it for advertising. AI processing runs on Amazon Bedrock; we send only the minimum content
needed for each operation (e.g. the posts being labeled or the question being answered).</p>

<h3>Where it lives</h3>
<p>Data is stored with our infrastructure providers — AWS (hosting, encryption, email) and Neon
(database), in US regions — protected by per-account isolation enforced at the database layer and
encryption for sensitive tokens. Transport is HTTPS everywhere.</p>

<h3>Cookies</h3>
<p>One session cookie to keep you signed in, and one preference cookie for your feed view.
If you arrive from an X ad, a first-party cookie briefly remembers the ad's click id so
that, if you then create an account, we can tell X that its ad resulted in a signup — that
single fact and nothing else (no third-party scripts, no cross-site tracking, and nothing
about what you save or ask). The click id expires after 30 days and is not kept on our
servers.</p>

<h3>Your rights</h3>
<p>Email <a href="mailto:{_CONTACT}">{_CONTACT}</a> to request an export of your data or deletion
of your account and everything in it — we'll complete either within 30 days. Disconnecting X
(or revoking the app in your X settings) stops all further bookmark access immediately.</p>

<h3>Changes</h3>
<p>Material changes to this policy will be reflected in the date above.</p>

<p><a href="/terms">Terms of Service</a></p>
"""
    return page("Privacy Policy", body)
