"""Persistence on Postgres (Neon) for bookmarks, authors, taxonomy, assignments, vectors.

Multi-tenant from the schema down: every tenant-owned table carries a ``tenant_id`` that
defaults from the ``app.current_tenant`` session GUC, and Row-Level Security policies scope
reads/writes to it. The app sets the GUC once per connection (see ``connect``).

Isolation status: the policies are defined and FORCEd now, so the schema is "tenant-ready".
DB-enforced isolation becomes airtight once the app connects as a restricted (non-owner)
role — that lands with multi-tenant auth (plan Inc 3). Until then there is a single tenant
(you), so there is no other tenant's data to leak regardless. Writes are already stamped
with the right ``tenant_id`` via the column DEFAULT.

Vectors live in the ``embeddings`` table as pgvector ``vector(1024)`` with an HNSW cosine
index; semantic search is a single ``ORDER BY vector <=> query`` in ``search.py``.
"""

from __future__ import annotations

import os

import psycopg
from pgvector.psycopg import register_vector

from .config import DEFAULT_TENANT_ID


def _tenant(tenant_id: str | None) -> str:
    """Resolve the active tenant: explicit arg, else env, else the single-user default."""
    return tenant_id or os.getenv("XBB_TENANT_ID", DEFAULT_TENANT_ID)

# Tables owned by a tenant (get tenant_id + RLS). Order matters for FK creation.
_TENANT_TABLES = ("authors", "posts", "self_thread_posts", "categories", "assignments",
                  "embeddings", "sync_state", "usage_events")

# current_setting(..., true) = missing_ok: returns NULL if the GUC is unset, so an
# unscoped connection writes NULL into a NOT NULL column (fails closed) and matches no rows.
_TENANT_DEFAULT = "current_setting('app.current_tenant', true)::uuid"

SCHEMA = f"""
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS accounts (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),  -- this id IS the tenant_id
    email      text UNIQUE NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS authors (
    tenant_id     uuid NOT NULL DEFAULT {_TENANT_DEFAULT},
    id            text NOT NULL,
    handle        text,
    display_name  text,
    avatar_url    text,
    PRIMARY KEY (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS posts (
    tenant_id      uuid NOT NULL DEFAULT {_TENANT_DEFAULT},
    id             text NOT NULL,        -- X post id, with tenant_id the upsert target
    source         text NOT NULL DEFAULT 'x',
    url            text,
    text           text,
    lang           text,
    created_at     text,
    bookmarked_at  text,
    author_id      text,
    kind           text,                 -- 'original' | 'reply' | 'quote'
    parent_post_id text,
    media_json     text,                 -- [{{url, alt_text, type}}]
    hashtags_json  text,
    links_json     text,
    like_count     integer,
    repost_count   integer,
    raw_json       text,                 -- original X payload, retained verbatim
    bm_rank        bigint,               -- bookmark-recency rank; higher = more recently saved
    label_attempted integer,             -- 1 once labeling has been tried
    PRIMARY KEY (tenant_id, id),
    FOREIGN KEY (tenant_id, author_id) REFERENCES authors (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS self_thread_posts (
    tenant_id    uuid NOT NULL DEFAULT {_TENANT_DEFAULT},
    root_post_id text NOT NULL,
    position     integer NOT NULL,
    post_id      text NOT NULL,
    PRIMARY KEY (tenant_id, root_post_id, position)
);

CREATE TABLE IF NOT EXISTS categories (
    tenant_id  uuid NOT NULL DEFAULT {_TENANT_DEFAULT},
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- globally unique surrogate
    name       text,
    definition text,
    parent     text,
    UNIQUE (tenant_id, name)
);

CREATE TABLE IF NOT EXISTS assignments (
    tenant_id   uuid NOT NULL DEFAULT {_TENANT_DEFAULT},
    post_id     text NOT NULL,
    category_id bigint NOT NULL REFERENCES categories (id),
    PRIMARY KEY (tenant_id, post_id, category_id)   -- multi-label, one row per (post, category)
);

CREATE TABLE IF NOT EXISTS embeddings (
    tenant_id uuid NOT NULL DEFAULT {_TENANT_DEFAULT},
    post_id   text NOT NULL,
    vector    vector(1024),
    PRIMARY KEY (tenant_id, post_id)
);

CREATE INDEX IF NOT EXISTS embeddings_vector_hnsw
    ON embeddings USING hnsw (vector vector_cosine_ops);

CREATE TABLE IF NOT EXISTS sync_state (
    tenant_id uuid NOT NULL DEFAULT {_TENANT_DEFAULT},
    key       text NOT NULL,   -- e.g. 'bookmarks_cursor', 'x_oauth'
    value     text,
    PRIMARY KEY (tenant_id, key)
);

CREATE TABLE IF NOT EXISTS usage_events (
    tenant_id     uuid NOT NULL DEFAULT {_TENANT_DEFAULT},
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts            timestamptz NOT NULL DEFAULT now(),
    model         text,
    input_tokens  integer,
    output_tokens integer,
    cost_usd      double precision     -- metered at the AI seam (see usage.cost_of)
);
"""


def _apply_rls(con: psycopg.Connection) -> None:
    """Enable + FORCE RLS and (re)create the tenant-isolation policy on every tenant table."""
    for table in _TENANT_TABLES:
        con.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        con.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        con.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        con.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING (tenant_id = {_TENANT_DEFAULT}) "
            f"WITH CHECK (tenant_id = {_TENANT_DEFAULT})"
        )


def _execscript(con: psycopg.Connection, sql: str) -> None:
    """Run a multi-statement DDL script (psycopg sends one command per execute)."""
    no_comments = "\n".join(line.split("--", 1)[0] for line in sql.splitlines())
    for stmt in (s.strip() for s in no_comments.split(";")):
        if stmt:
            con.execute(stmt)


# The restricted role the web app connects as so RLS is actually enforced (it lacks BYPASSRLS,
# unlike the Neon owner). Created out-of-band by scripts/setup_app_role.py; granted here if present.
APP_ROLE = "xbb_app"


def _apply_grants(con: psycopg.Connection) -> None:
    """Grant connect/table/sequence privileges to the restricted app role, if it exists."""
    db = con.execute("SELECT current_database()").fetchone()[0]
    con.execute(
        f"""
        DO $$
        BEGIN
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{APP_ROLE}') THEN
            GRANT CONNECT ON DATABASE "{db}" TO {APP_ROLE};
            GRANT USAGE ON SCHEMA public TO {APP_ROLE};
            GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO {APP_ROLE};
            GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO {APP_ROLE};
          END IF;
        END $$;
        """
    )


def init_db(dsn: str, tenant_id: str | None = None) -> None:
    """Create the extension, tables, vector index, RLS policies, grants, default account.

    Safe to run repeatedly. Run as the database owner (DDL); the app connects as APP_ROLE.
    """
    tid = _tenant(tenant_id)
    with psycopg.connect(dsn) as con:
        con.execute("SELECT set_config('app.current_tenant', %s, false)", (tid,))
        _execscript(con, SCHEMA)
        _apply_rls(con)
        _apply_grants(con)
        # Seed the account row for the default/single-user tenant so its tenant_id is valid.
        con.execute(
            "INSERT INTO accounts (id, email) VALUES (%s, %s) ON CONFLICT (id) DO NOTHING",
            (tid, "local@x-bookmark-brain"),
        )
        con.commit()


def connect(dsn: str, tenant_id: str | None = None) -> psycopg.Connection:
    """Open a tenant-scoped connection: bind app.current_tenant and register the vector type."""
    con = psycopg.connect(dsn)
    con.execute("SELECT set_config('app.current_tenant', %s, false)", (_tenant(tenant_id),))
    con.commit()
    register_vector(con)
    return con


# --------------------------------------------------------------------------- key/value state
# RLS scopes these to the current tenant; inserts get tenant_id from the column DEFAULT.


def get_state(con: psycopg.Connection, key: str) -> str | None:
    """Read an arbitrary value from the sync_state store (e.g. OAuth tokens JSON)."""
    row = con.execute("SELECT value FROM sync_state WHERE key = %s", (key,)).fetchone()
    return row[0] if row and row[0] else None


def set_state(con: psycopg.Connection, key: str, value: str | None) -> None:
    """Write/clear an arbitrary sync_state value."""
    if value is None:
        con.execute("DELETE FROM sync_state WHERE key = %s", (key,))
    else:
        con.execute(
            "INSERT INTO sync_state (key, value) VALUES (%s, %s) "
            "ON CONFLICT (tenant_id, key) DO UPDATE SET value = excluded.value",
            (key, value),
        )
    con.commit()


def get_or_create_account(con: psycopg.Connection, email: str) -> str:
    """Return the account id for an email, creating the account on first sign-in. (No RLS on
    accounts — it's the tenant registry, queried by email before a tenant is known.)"""
    row = con.execute("SELECT id FROM accounts WHERE email = %s", (email,)).fetchone()
    if row:
        return str(row[0])
    row = con.execute(
        "INSERT INTO accounts (email) VALUES (%s) RETURNING id", (email,)
    ).fetchone()
    con.commit()
    return str(row[0])


def get_account_email(con: psycopg.Connection, account_id: str) -> str | None:
    row = con.execute("SELECT email FROM accounts WHERE id = %s", (account_id,)).fetchone()
    return row[0] if row else None


# --------------------------------------------------------------------------- usage metering


def record_usage(con: psycopg.Connection, model: str, input_tokens: int,
                 output_tokens: int, cost_usd: float) -> None:
    """Record one metered AI call for the current tenant (RLS stamps tenant_id)."""
    con.execute(
        "INSERT INTO usage_events (model, input_tokens, output_tokens, cost_usd) "
        "VALUES (%s, %s, %s, %s)",
        (model, input_tokens, output_tokens, cost_usd),
    )
    con.commit()


def usage_this_month(con: psycopg.Connection) -> float:
    """Total metered spend (USD) for the current tenant since the start of this month."""
    row = con.execute(
        "SELECT COALESCE(SUM(cost_usd), 0) FROM usage_events "
        "WHERE ts >= date_trunc('month', now())"
    ).fetchone()
    return float(row[0]) if row else 0.0


def get_sync_cursor(con: psycopg.Connection) -> str | None:
    """The saved bookmarks pagination cursor to resume from, or None (never started / done)."""
    return get_state(con, "bookmarks_cursor")


def set_sync_cursor(con: psycopg.Connection, cursor: str | None) -> None:
    """Persist where the next backfill should resume. None clears it (the sync finished)."""
    set_state(con, "bookmarks_cursor", cursor)
